// The one-line install path.
//
//   curl -fsSL http://10.1.1.171:8080/install/<token> | sudo bash
//
// Run on the machine being monitored, by whoever already has root there. That
// removes three things from the old route: an account on the central server,
// an ssh hop, and any need for the person to handle the agent key.
//
// The response is one self-contained script with the agent files embedded, so
// redeeming the token is a single request — there is no second fetch that would
// need its own authentication, and the token can be marked spent the moment it
// is used.
import path from 'node:path';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { requireRole, audit, generateAgentKey, sha256 } from '../lib/auth.js';
import { q, pool } from '../db/pool.js';
import { mintInstallToken, redeemInstallToken } from '../lib/install-token.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Everything the target needs. install.sh treats monit-config.sh, check-ndb.sh
// and monit-pm2.sh as optional, but shipping them means `monit-config.sh` and
// the NDB check are there later without a second visit.
const AGENT_FILES = [
  'monit-agent.sh',
  'install.sh',
  'monit-agent.service',
  'monit-config.sh',
  'monit-pm2.sh',
  'check-ndb.sh',
  'agent.conf.example',
];

// Bare-metal runs from the repo; the container has agent/ copied next to src/.
const AGENT_DIRS = [
  path.join(__dirname, '../../../agent'),   // repo checkout
  path.join(__dirname, '../../agent'),      // docker image
];

export function agentDir() {
  return AGENT_DIRS.find((d) => existsSync(path.join(d, 'monit-agent.sh'))) || null;
}

let cache = null;
async function agentPayload() {
  const dir = agentDir();
  if (!dir) {
    throw Object.assign(new Error(
      'the agent files are not present next to the server — this build cannot serve the one-line installer'),
    { statusCode: 503 });
  }
  const stamp = dir;
  if (cache?.stamp === stamp) return cache.files;
  const files = {};
  for (const f of AGENT_FILES) {
    const p = path.join(dir, f);
    if (existsSync(p)) files[f] = (await readFile(p)).toString('base64');
  }
  cache = { stamp, files };
  return files;
}

/**
 * Where agents should post.
 *
 * Prefer what an admin configured. When nothing is configured, fall back to the
 * address this very request arrived on: it is a guess, but it is a guess that
 * demonstrably reaches the server, which beats handing someone a command with a
 * placeholder in it and a disabled button. `source` lets the caller say which
 * of the two it is instead of passing a guess off as settled.
 */
export async function agentBaseUrl(req) {
  const { rows } = await q(`SELECT value FROM app_settings WHERE key = 'agent_api_url'`);
  if (rows[0]?.value) return { url: String(rows[0].value).replace(/\/+$/, ''), source: 'setting' };
  const proto = req.headers['x-forwarded-proto'] || req.protocol || 'http';
  const host = req.headers['x-forwarded-host'] || req.headers.host;
  const prefix = String(req.headers['x-forwarded-prefix'] || '').replace(/\/+$/, '');
  return { url: host ? `${proto}://${host}${prefix}` : '', source: host ? 'request' : 'none' };
}

export const installCommand = (base, token) => `curl -sSL ${base}/install/${token} | sudo bash`;

const shq = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;

/**
 * A refusal that still says something useful when it is piped into bash.
 *
 * The obvious thing — comment lines explaining the problem — is exactly wrong
 * here: bash prints nothing for a comment, so the person sees a completely
 * silent failure. Adding `-f` to their curl is no better; it replaces the body
 * with `curl: (22) … error: 410`, which is not an explanation either. So a
 * refusal is a tiny script whose whole job is to print the reason and exit
 * non-zero.
 */
function refusal(lines) {
  const say = lines.map((l) => `echo ${shq(l)} >&2`).join('\n');
  return `#!/usr/bin/env bash\n${say}\nexit 1\n`;
}

/**
 * The script the target runs. It is written to fail loudly and early: a wrong
 * base URL, a missing curl, or a non-root shell all stop before anything is
 * written to the filesystem.
 *
 * Everything sits inside a function that is called on the last line. A pipe to
 * bash executes what has arrived so far, so a transfer cut off halfway would
 * otherwise run half an installer; this way an incomplete download simply never
 * calls anything.
 */
function bootstrap({ files, apiUrl, serverId, apiKey, mode }) {
  const unpack = Object.entries(files)
    .map(([name, b64]) => `  printf %s ${shq(b64)} | base64 -d > "$D"/${name}`)
    .join('\n');

  return `#!/usr/bin/env bash
# monit agent installer for '${serverId}'.
# Generated by the monit dashboard; the token that produced it is now spent.
set -euo pipefail

# Global, not local to the function: the EXIT trap fires after the function has
# returned, and under \`set -u\` a local would be unbound by then — turning any
# failed install into a confusing "D: unbound variable" on the way out.
__monit_D=""
# shellcheck disable=SC2064
trap 'rm -rf "\${__monit_D:-}"' EXIT

__monit_install() {
  red() { printf '\\033[31m✗ %s\\033[0m\\n' "$*" >&2; }

  if [ "$(id -u)" != 0 ]; then
    red "run this with sudo:"
    echo "   curl -sSL ${apiUrl}/install/<token> | sudo bash" >&2
    return 1
  fi
  command -v base64 >/dev/null 2>&1 || { red "base64 is required"; return 1; }
  command -v curl   >/dev/null 2>&1 || { red "curl is required";   return 1; }

  # The key exists in this directory for the length of the install and nowhere
  # else; the trap above clears it on every exit path, including a failure.
  __monit_D=$(mktemp -d /tmp/monit-install.XXXXXX)
  local D=$__monit_D
  chmod 700 "$D"

${unpack}
  chmod +x "$D"/*.sh

  "$D"/install.sh ${shq(apiUrl)} ${shq(serverId)} ${shq(apiKey)} ${shq(mode)}
}

__monit_install "$@"
`;
}

export default async function installRoutes(app) {
  // ---- mint a token for a server that already exists ------------------------
  // This replaces the server's current key: the point of asking for one is that
  // nobody has a working key any more. The dashboard says so before calling.
  app.post('/api/v1/servers/:id/install-token', {
    preHandler: requireRole('operator'),
  }, async (req, reply) => {
    const id = req.params.id;
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      const { rows } = await client.query(
        'SELECT id FROM servers WHERE id = $1 AND archived_at IS NULL FOR UPDATE', [id]);
      if (!rows[0]) {
        await client.query('ROLLBACK');
        return reply.code(404).send({ title: 'Not found', status: 404 });
      }
      const apiKey = generateAgentKey();
      await client.query(
        'UPDATE api_keys SET revoked_at = now() WHERE server_id = $1 AND revoked_at IS NULL', [id]);
      await client.query('INSERT INTO api_keys (server_id, key_hash) VALUES ($1,$2)', [id, sha256(apiKey)]);
      await client.query('COMMIT');

      const { token, expiresAt, ttlMinutes } = await mintInstallToken({
        serverId: id, apiKey, userId: req.user?.sub || null,
      });
      await audit(req, 'install.token', 'server', id, { ttl_minutes: ttlMinutes });

      const base = await agentBaseUrl(req);
      return {
        token,
        expires_at: expiresAt,
        ttl_minutes: ttlMinutes,
        base_url: base.url,
        base_url_source: base.source,   // 'setting' = configured, 'request' = inferred
        // No -f: with it, curl swallows the body on a 4xx and the person is
        // told nothing when a link has already been used or has expired.
        command: installCommand(base.url, token),
        replaced_key: true,
      };
    } catch (e) {
      await client.query('ROLLBACK');
      throw e;
    } finally {
      client.release();
    }
  });

  // ---- redeem ---------------------------------------------------------------
  // Deliberately unauthenticated: the token is the credential, it is good once,
  // and it expires. Anything stronger would mean the person installing needs an
  // account here, which is exactly what this route exists to avoid.
  app.get('/install/:token', async (req, reply) => {
    const mode = req.query?.mode === 'cron' ? 'cron' : 'loop';
    let claim;
    try {
      claim = await redeemInstallToken(req.params.token, req.ip);
    } catch (e) {
      req.log.warn({ reason: e.reason }, 'install token rejected');
      return reply.code(e.reason === 'unknown' ? 404 : 410)
        .type('text/x-shellscript; charset=utf-8')
        .send(refusal([
          `✗ ${e.message}`,
          '',
          '  An install link works on one machine and expires 15 minutes after it is created.',
          '  In the dashboard, open the server and press "Install command" for a fresh one.',
        ]));
    }

    let files;
    try {
      files = await agentPayload();
    } catch (e) {
      req.log.error(e, 'agent files missing');
      return reply.code(503).type('text/x-shellscript; charset=utf-8').send(refusal([
        `✗ ${e.message}`,
        '',
        '  Install from the central server with ./deploy-agent.sh instead,',
        '  or rebuild the image so agent/ ships with it.',
      ]));
    }

    const apiUrl = (await agentBaseUrl(req)).url;
    req.log.info({ server_id: claim.serverId, ip: req.ip }, 'install token redeemed');

    return reply
      .type('text/x-shellscript; charset=utf-8')
      // Not cached anywhere: the body carries an agent key.
      .header('cache-control', 'no-store')
      .send(bootstrap({ files, apiUrl, serverId: claim.serverId, apiKey: claim.apiKey, mode }));
  });
}
